version: 2
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales info
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"
          - not_null:
              column_name: "(orders_id || '_' || pdt_id)"
      - name: product
        identifier: raw_gz_products
        description: all products
        tests:
          - unique:
              column_name: products_id
          - not_null: 
              column_name: products_id
      - name: ship
        identifier: raw_gz_ship
        description: shipping info
        tests:
          - unique: 
              column_name: orders_id
      - name: adwords 
        identifier: raw_gz_adwords
      - name: bing 
        identifier: raw_gz_bing
      - name: criteo 
        identifier: raw_gz_criteo
      - name: facebook 
        identifier: raw_gz_facebook
        
